sudo: required
services:
  - docker
before_install:
  - docker build -t naveen/react -f Dockerfile.dev .

script: 
  - docker run naveen/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-730942267492"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"
